swagger: "2.0"
info:
  version: "1.0.0"
  title: "Vault client"
basePath: "/"
schemes:
- "http"
paths:
  /sts/{eventType}:
    get:
      summary: "Publish SyndicationEvent to SNS"
      description: "Publishes a message to the topic. This functionality is for debugging purposes and may be disabled."
      operationId: "sendSyndicationEventToSns"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "eventType"
        type: "string"
        description: "The type of SyndicationEvent being sent"
        required: true
      - in: "body"
        name: "body"
        description: "the SyndicationEvent to create"
        schema:
          type: string
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PublishResponse"
        400:
          description: "Invalid input"
        405:
          description: "Endpoint is disabled"
  /transit/{eventId}:
    get:
      summary: "Get an event"
      description: "Return an event by ID"
      operationId: "getEventById"
      produces:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        description: "EventId to get"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/EventResponse"
        404:
          description: "eventId not found"
  /event/resend:
    post:
      summary: "Resend a list of events"
      description: "Put events on the SNS topic"
      operationId: "resendEventsById"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "eventIds"
        description: "List of event ids to resend"
        required: true
        schema:
          type: "array"
          items:
            type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ResendResponse"
        404:
          description: "eventId not found"
definitions:
  EventResponse:
    type: "object"
    properties:
      eventType:
        type: "string"
      event:
        type: "string"
  ResendResponse:
    type: "object"
    properties:
      eventId:
        type: "string"
      messageId:
        type: "string"
  PublishResponse:
    type: "object"
    properties:
      messageId:
        type: "string"
